graphql:
    playground:
        endpoint: /graphql
        mapping: /playground
    servlet:
        exception-handlers-enabled: true
        max-query-depth: 20
logging:
    level:
        org:
            springframework:
                data:
                    neo4j: DEBUG
spring:
    application:
        name: pins-api
    neo4j:
        authentication:
            password: root
            username: neo4j
        uri: bolt://localhost:7687
voyager:
    enabled: true
